# bash_aliases

alias dfh='df -h | grep -v snap'
# Colorful output
alias grep='grep --color=always'
alias ls='ls --color=auto'
alias ll='ls -alF'
alias la='ls -A'

# Docker Compose 
if [ -x "$(command -v docker-compose)" ]; then
    alias dc="$(command -v docker-compose)"
elif [ -x "$(command -v docker)" ]; then
    alias dc="$(command -v docker) compose"
fi

# tmux color fix
#alias tmux='tmux -2'
#alias tmux='tmux attach'

# Remove snapcraft cruft from lsblk & df
#if [ -x "$(command -v snap)" ]; then
#	alias lsblk='lsblk -o name,mountpoint,label,size,fstype,uuid | grep -v ^loop'
#	alias df='df | grep -v /dev/loop'
#fi
